spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/to_do_list
    username: postgres
    password: Eldos2812
  jpa:
    hibernate:
        ddl-auto: update
    show-sql: true
server:
  port: 8081
logging:
  level:
    sql: trace